
package com.redhat.brq.integration.examination.supplier.a;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnkownItemException", targetNamespace = "urn:com.redhat.sysint.exam:supplier-a")
public class UnkownItemException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnkownItemException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UnkownItemException(String message, UnkownItemException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UnkownItemException(String message, UnkownItemException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: exam.sysint.redhat.com.supplier_a.UnkownItemException
     */
    public UnkownItemException getFaultInfo() {
        return faultInfo;
    }

}
